### PR TITLE
fix: child modules need required providers source oracle/oci

### PR DESCRIPTION
**Pull request by christophercorn**
see here: https://github.com/oracle-terraform-modules/terraform-oci-logging/issues/15

### CODE REVIEW

**Comment by christophercorn** [comment]
Hi @hyder @devoncrouse  Can someone review this? Thanks.

**Review by hyder — APPROVED** [review]
Approved. Thank you for your contribution.

**Comment by hyder** [comment]
Would you like us to cut a new release @christophercorn ?

**Comment by christophercorn** [comment]
> Would you like us to cut a new release @christophercorn ?

do you have any instruction for that @hyder

**Comment by hyder** [comment]
We'll cut a new release if you are using the module remotely through the Terraform registry instead of github here.

**Comment by christophercorn** [comment]
> We'll cut a new release if you are using the module remotely through the Terraform registry instead of github here.

yeah, that would be great to use this module through terraform registry.

**Pull request merged**
