### PR TITLE
mediaflow log added

### PR DESCRIPTION
**Pull request by karthicgit**
Logging for mediaflow service added.

### CODE REVIEW

**Comment by Djelibeybi** [comment]
@karthicgit, please make your membership of github.com/oracle public so that the OCA bot can verify it.

**Comment by karthicgit** [comment]
@Djelibeybi Its done . Do i need to close this PR and raise a new one ?

**Comment by Djelibeybi** [comment]
@karthicgit nope.

**Comment by karthicgit** [comment]
@hyder could you please review it

**Review by hyder — APPROVED** [review]
approved

**Pull request merged**
